// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

import * as pulumiAws from "@pulumi/aws";

export class Vpc extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'aws-vpc:index:Vpc';

    /**
     * Returns true if the given object is an instance of Vpc.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Vpc {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Vpc.__pulumiType;
    }

    declare public readonly baseTags: pulumi.Output<outputs.Tags>;
    declare public /*out*/ readonly internetGateway: pulumi.Output<pulumiAws.ec2.InternetGateway>;
    declare public /*out*/ readonly name: pulumi.Output<string>;
    declare public /*out*/ readonly natElasticIpAddresses: pulumi.Output<pulumiAws.ec2.Eip[]>;
    declare public /*out*/ readonly natGateways: pulumi.Output<pulumiAws.ec2.NatGateway[]>;
    declare public /*out*/ readonly privateRouteTables: pulumi.Output<pulumiAws.ec2.RouteTable[]>;
    declare public /*out*/ readonly privateSubnets: pulumi.Output<pulumiAws.ec2.Subnet[]>;
    declare public /*out*/ readonly publicRouteTable: pulumi.Output<pulumiAws.ec2.RouteTable>;
    declare public /*out*/ readonly publicSubnets: pulumi.Output<pulumiAws.ec2.Subnet[]>;
    declare public /*out*/ readonly vpc: pulumi.Output<pulumiAws.ec2.Vpc>;

    /**
     * Create a Vpc resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VpcArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.availabilityZoneNames === undefined && !opts.urn) {
                throw new Error("Missing required property 'availabilityZoneNames'");
            }
            if (args?.baseCidr === undefined && !opts.urn) {
                throw new Error("Missing required property 'baseCidr'");
            }
            if (args?.baseTags === undefined && !opts.urn) {
                throw new Error("Missing required property 'baseTags'");
            }
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            resourceInputs["availabilityZoneNames"] = args?.availabilityZoneNames;
            resourceInputs["baseCidr"] = args?.baseCidr;
            resourceInputs["baseTags"] = args?.baseTags;
            resourceInputs["description"] = args?.description;
            resourceInputs["internetGateway"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["natElasticIpAddresses"] = undefined /*out*/;
            resourceInputs["natGateways"] = undefined /*out*/;
            resourceInputs["privateRouteTables"] = undefined /*out*/;
            resourceInputs["privateSubnets"] = undefined /*out*/;
            resourceInputs["publicRouteTable"] = undefined /*out*/;
            resourceInputs["publicSubnets"] = undefined /*out*/;
            resourceInputs["vpc"] = undefined /*out*/;
        } else {
            resourceInputs["baseTags"] = undefined /*out*/;
            resourceInputs["internetGateway"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["natElasticIpAddresses"] = undefined /*out*/;
            resourceInputs["natGateways"] = undefined /*out*/;
            resourceInputs["privateRouteTables"] = undefined /*out*/;
            resourceInputs["privateSubnets"] = undefined /*out*/;
            resourceInputs["publicRouteTable"] = undefined /*out*/;
            resourceInputs["publicSubnets"] = undefined /*out*/;
            resourceInputs["vpc"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Vpc.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Vpc resource.
 */
export interface VpcArgs {
    availabilityZoneNames: string[];
    baseCidr: string;
    baseTags: inputs.TagsArgs;
    description: string;
}
